FROM nginx
MAINTAINER kkotari522@gmail.com
COPY app1 /usr/share/nginx/html/
# default nginx webserver location where I need to have my App.
EXPOSE 80
# default port of web server that container can use.

